apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress
data:
  WORDPRESS_DB_HOST: 10.245.136.110:3306
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: wordpress
  WORDPRESS_DB_NAME: wordpress
