apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec:
    containers:
    - name: nginx
      image: nginx:alpine
    - name: redis
      image: redis:latest
    - name: memcached
      image: memcached:latest
